services:
  test:
    image: eclipse-temurin:17-jdk
    container_name: "test"
    working_dir: /src
    command: ./mvnw clean spring-boot:run
    ports:
      - 8080:8080
    volumes:
      - ./:/src
      - "${HOME}/.m2:/root/.m2"
